server:
  shutdown: graceful
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/toy_cocktail
    username: cocktail
    password: 1234

decorator:
  datasource:
    p6spy:
      enable-logging: true #운영환경에서는 false
