server:
  shutdown: graceful
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/toy_cocktail
    username: cocktail
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create # 한번 실행 이후 무조건 update로 수정

decorator:
  datasource:
    p6spy:
      enable-logging: true #운영환경에서는 false
---
spring:
  config:
    activate:
      on-profile: init

  jpa:
    hibernate:
      ddl-auto: create
