server:
  shutdown: graceful
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/toy_cocktail
    username: cocktail
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update # 한번 실행 이후 무조건 update로 수정
  jwt:
    secret: ${JWT_SECRET_KEY}
decorator:
  datasource:
    p6spy:
      enable-logging: true #운영환경에서는 false

logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: init

  jpa:
    hibernate:
      ddl-auto: create

